version: '3.8'

x-shared:
  &common
  NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000 
  NEO4J_dbms_memory_pagecache_size: "100M" 
  NEO4J_dbms_memory_heap_initial__size: "100M" 

x-shared-core:
  &common-core
  <<: *common
  NEO4J_dbms_mode: CORE
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks: 
  lan:

services:

  core1:
    image: neo4j:${NEO4J_VERSION}
    networks:
      - lan 
    ports: 
      - "7474:7474"
      - "7687:7687"
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core1:5000 
      NEO4J_causal__clustering_transaction__advertised__address: core1:6000 
      NEO4J_causal__clustering_raft__advertised__address: core1:7000 

  core2:
    image: neo4j:${NEO4J_VERSION}
    networks:
      - lan
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      <<:  *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core2:5000
      NEO4J_causal__clustering_transaction__advertised__address: core2:6000
      NEO4J_causal__clustering_raft__advertised__address: core2:7000

  core3:
    image: neo4j:${NEO4J_VERSION}
    networks:
      - lan
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      <<:  *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core3:5000
      NEO4J_causal__clustering_transaction__advertised__address: core3:6000
      NEO4J_causal__clustering_raft__advertised__address: core3:7000

  readreplica1:
    image: neo4j:${NEO4J_VERSION}
    networks:
      - lan
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      <<:  *common
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_discovery__advertised__address: readreplica1:5000
      NEO4J_causal__clustering_transaction__advertised__address: readreplica1:6000
      NEO4J_causal__clustering_raft__advertised__address: readreplica1:7000
